#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl jq nix

set -euo pipefail

echo "Fetching latest Hytale Launcher version..."

# Obtener versión actual desde el API de Hytale
VERSION=$(curl -s https://launcher.hytale.com/version/release/launcher.json | jq -r .version)
URL="https://launcher.hytale.com/builds/release/linux/amd64/hytale-launcher-${VERSION}.zip"

echo "Latest version: $VERSION"
echo "Downloading and calculating hash..."

# Obtener hash usando nix-prefetch-url
HASH=$(nix-prefetch-url --type sha256 "$URL")
SRI_HASH=$(nix hash to-sri --type sha256 "$HASH")

# Escribir archivo de versión
cat >"$(dirname "$0")/source.nix" <<EOF
# Auto-generated by update.sh - do not edit manually
{
  version = "$VERSION";
  sha256 = "$SRI_HASH";
}
EOF

echo ""
echo "✓ Successfully updated to version: $VERSION"
echo "✓ Hash: $SRI_HASH"
echo ""
echo "Run 'nh os switch . #rift' to rebuild your system with the new version"
